### ISSUE TITLE
Drill page - New presentation

### ISSUE THREAD

**Issue by sallesma** [UltimateApp/UltimateApp#14]
Drill page should look like this : 
<img width="444" alt="Screenshot 2020-03-22 at 19 12 43" src="https://user-images.githubusercontent.com/3810795/77256889-2a007a00-6c71-11ea-9f2c-5b94a7da165a.png">

Should include all the info about the drill : equipment needed, number of players, space...

**Comment by guillaumemoby** [comment]
We could add a theoretical part under Equipment.
