### ISSUE TITLE
Training page

### ISSUE THREAD

**Issue by Adeloche** [UltimateApp/UltimateApp#19]
From Homepage, when user choose 'Training' he is redirected to a page showing all available trainings.
When he select a training, he is redirected to a page showing all drills from training

![image](https://user-images.githubusercontent.com/62174449/77257442-a0eb4200-6c74-11ea-89ff-188adf67622c.png)

**Comment by sallesma** [comment]
- Add a description for the session.

Maybe #53 should be done first ?
