### ISSUE TITLE
Moving an element remove the next counter cut

### ISSUE THREAD

**Issue by ZacharieALES** [UltimateApp/UltimateApp#210]
## 🐛 Bug Report
When moving an element at step i, the counter-cut of step i+1 (if any) is removed.

### Environment
iPad Air

### Steps to Reproduce
Add an element 
Go to step 2
Move the element 
Move its counter-cut
Go to step 1
Move the element

The counter-cut has disappeared.

### Expected Behavior
The counter-cut should not disappear.

### Actual Behavior
The counter-cut disappear.

**Comment by sallesma** [comment]
https://github.com/UltimateApp/UltimateApp/pull/192/commits/d84274142aabd9b415edbae733f6e99d7806fa34
