### ISSUE TITLE
Find a smart way to link the drills and training

### ISSUE THREAD

**Issue by guillaumemoby** [UltimateApp/UltimateApp#29]
I am looking for idea to link a series of exercises or trainings. This "series" will be made by experience coachs which will have to create coherent and thoughtful sequences adapted to a defined level.

Here is the list of my idea :
- At the end of the Training description or drills we could have a link to the next practice. I like this idea because being able to link drills together it's something difficult as a beginner coach
- We could add a fourth buttom on the homepage to add "Your next frisbee or fitness drill"

**Comment by sallesma** [comment]
Implemented with programs
