### ISSUE TITLE
[New page] Drill editor (video or animation)

### ISSUE THREAD

**Issue by guillaumemoby** [UltimateApp/UltimateApp#32]
We want the user being able to create their own drill. The animation is a key part of this app ,
we want to obtain something close to:
 https://www.ultiplays.com/invite/VeEqZ2DDZ1IM3eBBWM74

**Comment by guillaumemoby** [comment]
@ZacharieALES , maybe you can ask to someone to help you on this topics?

**Comment by ZacharieALES** [comment]
If anyone wants to help, I will be happy to have you.
I think it can be done in 1 week since we already have the definition of a drill.
For the drag and drop part I plan to follow this example:
https://blog.reactnativecoach.com/creating-draggable-component-with-react-native-132d30c27cb0

**Comment by sallesma** [comment]
Implemented in the app (thanks zach)
We'll make it better little by little
