### ISSUE TITLE
Video view --> full Screen 

### ISSUE THREAD

**Issue by guillaumemoby** [UltimateApp/UltimateApp#37]
Now, we (Martin) have succeed to present a video like this:
![videoscreen](https://user-images.githubusercontent.com/56125567/77684294-15d2ba80-6f9a-11ea-8e52-2be9e1fd4f26.PNG)

For a better visualization, we are aiming to a be able to have a full screen view.

 ![8 Drill Page Video Horizontal](https://user-images.githubusercontent.com/56125567/77683981-8decb080-6f99-11ea-9113-dc12511c7e90.PNG)

**Comment by guillaumemoby** [comment]
It seems that it's already work on ios emulator

**Comment by sallesma** [comment]
We have to think about it if the video is added to the bottom of the Drill page. Do we want to go full screen on device rotation even if the user is not playing the vidéo ?
