### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by tonnenpinguin** [UltimateApp/UltimateApp#4]
In order to enforce consistent quality and help with review we should have an automated pipeline running tests, etc. for us.

* Run tests, lint and prettier on all commits
* Add code climate?
* Publish master to Expo

**Comment by sallesma** [comment]
Maybe we could use Github Actions. It's for free on public repos, and I think it makes it easier not to introduce another third party tool

- https://medium.com/better-programming/iterate-faster-with-github-actions-for-react-native-55297e9975b4
- https://github.com/expo/expo-github-action

**Comment by sallesma** [comment]
- linting was introduced in https://github.com/UltimateApp/UltimateApp/pull/1 and precommit hooks added in https://github.com/UltimateApp/UltimateApp/pull/5
- Automated tests where introduced in https://github.com/UltimateApp/UltimateApp/pull/40 with github actions and enhanced with https://github.com/UltimateApp/UltimateApp/pull/47

I think we're good for now on CI
