### ISSUE TITLE
Filling the Database: Fitness and Technical Drills

### ISSUE THREAD

**Issue by guillaumemoby** [UltimateApp/UltimateApp#43]
There is a need to complete the database with the first real drill that will be integrate in the app.

For the fitness drill, we try to add video with a nice realization as on these examples:
https://www.youtube.com/channel/UCjNE2-Yeiwo4mTJ3HdfrSHA/videos
https://www.youtube.com/user/FitnessBlender/videos
https://www.youtube.com/channel/UCCgDGih2kSp0A6W_0cVYuaQ/videos
https://www.youtube.com/watch?v=tpVhJNQURk4
https://www.youtube.com/channel/UC_aLZ9YxRrGmCe1Zd3GSkEA/videos

@guillaumemoby : I will ask to the coaches in my network to share with us some drills that I will implement in the V1.

**Comment by guillaumemoby** [comment]
I will complete this google sheet to regroup the content I will find online:
https://docs.google.com/spreadsheets/d/1YJ2gjQ69U6fT22MpsDOdb0rpfwP57YMahj0wIMwFEo8/edit?usp=sharing

**Comment by guillaumemoby** [comment]
I need help to introduce a better structure in our data save in index.js



{
      id: 2,
      type: 'technical', // vs fitness
      source: 'Edwin Grappin',
      title: 'Defense Positioning',
      image:
        'https://www.plu.edu/recreations/wp-content/uploads/sites/197/2019/04/ultimate-frisbee-3-2-19-1122-scaled-1536x1163.jpg',
      description:
        '...',
      nbPlayers: 8,
      equipmentLabel: '',
      equipment: 'One disc, 2 cones, 3 players',
      durationInMinutes: 10,
      intensity: 'Moderate', // Low , High
      goals: ['Defense', 'Handling'], // Cutting , Throwing , Communication , Catch
      level: 'Beginner', // Intermediate , Advanced
      seasonTiming: 'Off-season', // / Pre-season , In-season , Anytime
      animation: '' , //if there is only one 1 animation to show complete with its name
      video: '' , // if there is only one 1 video to show complete with a youtube link
      steps: [
        {
          animation: animationSquare
          title: 'Version 1',
          subtitle: 'Focus on version 1',
        },
        {
          video: 'https://www.youtube.com/embed/vr8OToLRGyQ'
          title: 'New idea',
          subtitle: 'None',
        },
        {
          animation: animationSquare2
          title: 'Version 2',
          subtitle: 'Focus on version 2',
        },
      ],
    },

@sallesma , @punkylol , @tonnenpinguin, @Adeloche and @arribbar  
What do you tjink about the structure ?
Do you split in our data base Fitness drills and Frisbee Drills in two different table ?
How should we save our training ?

  training: [
    {
      id: 1,
      source: 'Rise Up',
      title: 'Dump & Swing',
      image: 'https://theaudl.com/sites/default/files/04282017%E2%80%94Minnesota%E2%80%94Cousins.jpg',
      description:
        '...t',
      nbPlayers: 2,
      equipment: 'One disc, 2 cones, 3 players',
      durationInMinutes: 15,
      goals: ['Catch', 'Handling'],
      level: 'intermediate',
      drills: [1, 2, 3, 4],
    },
],


Ps: I am trying to implement the enumeration on object to avoid spelling mistake

**Comment by tonnenpinguin** [comment]
I would use a structured object for the equipment, too.

```
equipment: [
    {
        count: 1,
        type: 'Disc'
    },
    {
        count: 2,
        type: 'Cone'
    },
]
```

PS: Wrap your code snippets with ``` to keep proper formatting in your comments :)

**Comment by sallesma** [comment]
I think everything from this issue was implemented for the V0
