### ISSUE TITLE
Display video in webview according to selected step

### ISSUE THREAD

**Issue by Adeloche** [UltimateApp/UltimateApp#9]
On a drill page, load animation/video associated to the selected step.

**Update**

On drill page we should have:

- Title
- Animation (video or 'ultiplay like' animation if provided, else display drill image), always the same
- Description
- (Optional) list of steps: just display them for version 0 if available, could be synchronized with animation in a later version

So for now a drill should have:

drill:
      id (integer),
      type (['fitness','technical']),
      title: (text),
      img: (image link)
      description: (text),
      nbPlayers: (integer),
      duration: (integer minutes)
      goals: [(keywords)],
      level: ['beginner'/'intermediate'/'advanced'],
      [optional] animation: (animation name),
      [optional] video: (link to video),
      [optional] steps: [
            {
              key: (integer),
              title: (text),
              subtitle: '(text),
            },
          ],

**Comment by Adeloche** [comment]
After talking with Moby, no need to have several videos depending on steps on a drill page.

On drill page we should have:
- Title
- Animation (video or 'ultiplay like' animation if provided, else display drill image)
- Subtitles
- (Optional) list of steps: just display them for  version 0 if available, could be synchronized with animation in a later version

**Comment by adelie1990** [comment]
Actually, according to new spec, this issue is cancelled :)
Though I do not have permission to do it. @guillaumemoby  ?

**Comment by Adeloche** [comment]
Wrong account, sorry :) Closing issue as it is not relevant anymore

**Comment by guillaumemoby** [comment]
Yep the video will be good enough. Thanks
